import numpy as np
import shap
from typing import Dict, List, Any

def explain(model: Any, feature_values: Dict[str, float], feature_names: List[str], background_data: np.ndarray = None) -> Dict[str, Any]:
    """
    Computes SHAP values to explain the risk score generated by an anomaly detection model.
    Provides numerical contributions and a faculty-readable natural language summary.
    
    Args:
        model: Trained sklearn model (IsolationForest, RandomForest, etc.)
        feature_values: Dictionary of a single student's features.
        feature_names: Ordered list of feature keys matching the model's training order.
        background_data: Optional 2D numpy array of background data for KernelExplainer fallback.
        
    Returns:
        Dict containing:
            - shap_values: Feature to SHAP value mapping.
            - top_risk_factors: Sorted list of features driving the risk.
            - natural_language_summary: Faculty-readable explanation string.
            - base_value: The base expected value of the model.
    """
    # 1. Prepare input array maintaining exact feature order
    x_row = np.array([[feature_values[fn] for fn in feature_names]])
    
    # Determine if it's IsolationForest where lower raw score = anomaly
    # If so, we'll invert the SHAP sign so positive SHAP = "increased risk"
    is_iforest = type(model).__name__ == "IsolationForest"
    
    # 2. Compute SHAP values
    try:
        # Try TreeExplainer first
        explainer = shap.TreeExplainer(model)
        shap_vals_obj = explainer.shap_values(x_row)
        expected_val_obj = explainer.expected_value
    except Exception:
        # Fallback to KernelExplainer
        if background_data is None:
            # Fallback to zeros if background data isn't provided
            background_data = np.zeros((1, len(feature_names)))
            
        # For sklearn models, prefer decision_function if available, otherwise predict
        predict_func = getattr(model, "decision_function", model.predict)
        explainer = shap.KernelExplainer(predict_func, background_data)
        shap_vals_obj = explainer.shap_values(x_row)
        expected_val_obj = explainer.expected_value

    # Parse TreeExplainer vs KernelExplainer output structures
    if isinstance(shap_vals_obj, list):
        # Depending on classification/anomaly, shap_values might be wrapped in a list
        shap_arr = shap_vals_obj[0]
        if isinstance(shap_arr, (list, np.ndarray)) and len(shap_arr) == 1:
            shap_arr = shap_arr[0]
    else:
        shap_arr = shap_vals_obj[0]

    if isinstance(expected_val_obj, (list, np.ndarray)):
        base_value = float(expected_val_obj[0])
    else:
        base_value = float(expected_val_obj)

    # 3. Process features and risk contributions
    shap_dict = {}
    factors = []
    
    for i, fname in enumerate(feature_names):
        raw_val = float(shap_arr[i])
        
        # Invert the value for IsolationForest so positive SHAP logically means "higher risk"
        # IsolationForest decision_function returns negative values for anomalies.
        # So a negative SHAP value pushes the score towards anomaly. 
        # By multiplying by -1, a positive value pushes the risk score higher.
        risk_val = -raw_val if is_iforest else raw_val
        
        shap_dict[fname] = risk_val
        
        direction = "increased risk" if risk_val > 0 else "decreased risk"
        factors.append({
            "feature": fname,
            "contribution": abs(risk_val),
            "actual_value": feature_values[fname],
            "raw_shap": risk_val,
            "direction": direction
        })

    # Sort by absolute contribution to find the top drivers
    factors.sort(key=lambda x: x["contribution"], reverse=True)
    
    top_risk_factors = [
        {"feature": f["feature"], "contribution": f["contribution"], "direction": f["direction"]} 
        for f in factors
    ]
    
    # 4. Generate Natural Language Summary
    total_impact = sum(f["contribution"] for f in factors)
    
    if total_impact < 1e-4:
        summary = "No significant risk factors detected. The submission closely aligns with typical baseline patterns."
    else:
        # Focus on factors that INCREASE risk
        risk_drivers = [f for f in factors if f["raw_shap"] > 0][:3]
        
        if not risk_drivers:
            summary = "The submission's metrics lean towards normal or expected performance, presenting very low risk."
        else:
            summary_parts = []
            for factor in risk_drivers:
                fname = factor["feature"]
                val = factor["actual_value"]
                human_name = fname.replace('_', ' ')
                
                # Contextual sentences based on feature types
                if "z_score" in fname or "grade_jump" in fname or "delta" in fname:
                    summary_parts.append(
                        f"Performance deviated significantly from the expected baseline ({human_name}: {val:.2f})."
                    )
                elif "type_token" in fname or "vocab" in fname:
                    summary_parts.append(
                        f"Vocabulary richness was highly anomalous ({human_name}: {val:.2f})."
                    )
                elif "time" in fname:
                    summary_parts.append(
                        f"Submission timing was irregular compared to normal patterns ({human_name}: {val:.2f})."
                    )
                elif "sentence" in fname or "word_length" in fname:
                    summary_parts.append(
                        f"Student's writing style deviated significantly from their baseline ({human_name}: {val:.2f})."
                    )
                else:
                    summary_parts.append(
                        f"The submission exhibited unusual {human_name} patterns (value: {val:.2f})."
                    )
            
            summary = " ".join(summary_parts)

    return {
        "shap_values": shap_dict,
        "top_risk_factors": top_risk_factors,
        "natural_language_summary": summary,
        "base_value": base_value
    }
